
class AirplainCompanyNames {

   public static Names: any[] = [
        "Orbital Flight Of Stairs Group",
        "BAE Systems",
        "Subsequent Airplane",
        "Free Fugitive",
        "Trusted Takeoff",
        "The Actual",
        "TechSolve",
        "Escape Place",
        "Disorderly Airplane Group",
        "White Trajectory Group",
        "The Arms Trade",
        "EngineeringDefense",
        "Infinito Aerospace",
        "TopFlight",
        "LongFlight",
        "OuterSpaceProviders",
        "Defense Strategies",
        "Wild Trajectory",
        "The Day Trajectory",
        "AeroSafe",
        "SkyRiders",
        "The First ",
        "Direct Trajectory",
        "Lockheed Martin",
        "Short Fledge",
        "American Aircraft",
        "HorizontalFlight",
        "Defense Innovations",
        "Highest Plane Place",
        "Homeland Secure",
        "Ignominious Jet Spot",
        "First Fledge ",
        "Forward Flying ",
        "Ordnance technologies",
        "Atmospherica",
        "TechTalent",
        "Sanaro corp",
        "Massive Aircraft Trading Co",
        "The Powered Plane ",
        "Defenseinstincts global",
        "AeroAssurance",
        "MileFlight ",
        "The Brief Flight Of Stairs",
        "OuterSpaceContracts",
        "Exelis Inc.",
        "Speed Escape Collective",
        "Forward Aircraft ",
        "Shameful Takeoff ",
        "Armored Air",
        "Flight Of Steps Pro ",
        "Trajectory Spot ",
        "Dynamic Technologies",
        "AeroTechDefense",
        "Aeroaware",
        "Flyover Foundation",
        "Airplane Place ",
        "Aerospace Systems",
        "Horizontal Jet Collective",
        "Regal technologies",
        "Air Innovations",
        "Extreme Innovations",
        "QuickFlight ",
        "Commercial Fledge",
        "BlueSky Corp",
        "Firth Rixson",
        "Aerospace Engineering Solutions",
        "The Aerial Escape ",
        "Ironclad Air",
        "Full Flier ",
        "Double Jet Trading Co",
        "Leonardo",
        "Novar technology",
        "Disorderly Plane Co",
        "OuterSpaceTech",
        "Steel Systems",
        "DefenseTechSolutions",
        "Mile Trajectory Group ",
        "The Short ",
        "The Top ",
        "kratos defence tech",
        "Routine Jet Pro ",
        "Eminence Avionics",
        "Orbital Jet ",
        "Nonstop Jet Collective",
        "First Takeoff Group ",
        "Country Jet Trading Co",
        "Volts aerospace",
        "Bell - Aire",
        "Atlantic Airplane Spot",
        "Raytheon",
        "The Horizontal Flight Of Stairs",
        "DefenseContracting",
        "Known Aeronautical",
        "Narrow Takeoff Pro ",
        "The Available ",
        "puissance aerospace",
        "NanoSolutions"

    ]



}
export default AirplainCompanyNames;